#ifdef USE_GURO_HTFL_HT_015_03
static const unsigned char* guro_htfl_ht_015_03_data = nullptr;
#endif
#ifdef USE_GURO_SCFL_HT_015_03
static const unsigned char* guro_scfl_ht_015_03_data = nullptr;
#endif
#ifdef USE_L400_SNR_DCFL_HT_03
static const unsigned char l400_snr_dcfl_ht_03_data[] = {
#include "data/l400_snr_dcfl_ht_03.inc"
};
#endif
#ifdef USE_L400_SNR_DEFL_HT_03
static const unsigned char l400_snr_defl_ht_03_data[] = {
#include "data/l400_snr_defl_ht_03.inc"
};
#endif
#ifdef USE_L400_SNR_DRFL_HT_03
static const unsigned char l400_snr_drfl_ht_03_data[] = {
#include "data/l400_snr_drfl_ht_03.inc"
};
#endif
#ifdef USE_L400_SNR_LCFL_HT_03
static const unsigned char l400_snr_lcfl_ht_03_data[] = {
#include "data/l400_snr_lcfl_ht_03.inc"
};
#endif
#ifdef USE_L400_SNR_LEFL_HT_03
static const unsigned char l400_snr_lefl_ht_03_data[] = {
#include "data/l400_snr_lefl_ht_03.inc"
};
#endif
#ifdef USE_L400_SNR_LRFL_HT_03
static const unsigned char l400_snr_lrfl_ht_03_data[] = {
#include "data/l400_snr_lrfl_ht_03.inc"
};
#endif
#ifdef USE_L400_SNR_OFFL_HT_03
static const unsigned char l400_snr_offl_ht_03_data[] = {
#include "data/l400_snr_offl_ht_03.inc"
};
#endif
#ifdef USE_L400_SNR_XSFL_HT_03
static const unsigned char l400_snr_xsfl_ht_03_data[] = {
#include "data/l400_snr_xsfl_ht_03.inc"
};
#endif
#ifdef USE_LWFI_SNR_DCFL_HT_03
static const unsigned char lwfi_snr_dcfl_ht_03_data[] = {
#include "data/lwfi_snr_dcfl_ht_03.inc"
};
#endif
#ifdef USE_LWFI_SNR_DEFL_HT_03
static const unsigned char lwfi_snr_defl_ht_03_data[] = {
#include "data/lwfi_snr_defl_ht_03.inc"
};
#endif
#ifdef USE_LWFI_SNR_DRFL_HT_03
static const unsigned char lwfi_snr_drfl_ht_03_data[] = {
#include "data/lwfi_snr_drfl_ht_03.inc"
};
#endif
#ifdef USE_LWFI_SNR_LCFL_HT_03
static const unsigned char lwfi_snr_lcfl_ht_03_data[] = {
#include "data/lwfi_snr_lcfl_ht_03.inc"
};
#endif
#ifdef USE_LWFI_SNR_LEFL_HT_03
static const unsigned char lwfi_snr_lefl_ht_03_data[] = {
#include "data/lwfi_snr_lefl_ht_03.inc"
};
#endif
#ifdef USE_LWFI_SNR_LRFL_HT_03
static const unsigned char lwfi_snr_lrfl_ht_03_data[] = {
#include "data/lwfi_snr_lrfl_ht_03.inc"
};
#endif
#ifdef USE_LWFI_SNR_OFFL_HT_03
static const unsigned char lwfi_snr_offl_ht_03_data[] = {
#include "data/lwfi_snr_offl_ht_03.inc"
};
#endif
#ifdef USE_LWFI_SNR_XSFL_HT_03
static const unsigned char lwfi_snr_xsfl_ht_03_data[] = {
#include "data/lwfi_snr_xsfl_ht_03.inc"
};
#endif
#ifdef USE_PSTE_CRSH_CNFL_HT_015_03
static const unsigned char pste_crsh_cnfl_ht_015_03_data[] = {
#include "data/pste_crsh_cnfl_ht_015_03.inc"
};
#endif
#ifdef USE_PSTE_CRSH_EGFL_HT_015_03
static const unsigned char pste_crsh_egfl_ht_015_03_data[] = {
#include "data/pste_crsh_egfl_ht_015_03.inc"
};
#endif
#ifdef USE_PSTE_RIDE_BLFL_HT_03
static const unsigned char pste_ride_blfl_ht_03_data[] = {
#include "data/pste_ride_blfl_ht_03.inc"
};
#endif
#ifdef USE_PSTE_RIDE_CNFL_HT_03
static const unsigned char pste_ride_cnfl_ht_03_data[] = {
#include "data/pste_ride_cnfl_ht_03.inc"
};
#endif
#ifdef USE_PSTE_RIDE_EGFL_HT_03
static const unsigned char pste_ride_egfl_ht_03_data[] = {
#include "data/pste_ride_egfl_ht_03.inc"
};
#endif
#ifdef USE_RGRS_FTOM_CNFL_HT_03
static const unsigned char rgrs_ftom_cnfl_ht_03_data[] = {
#include "data/rgrs_ftom_cnfl_ht_03.inc"
};
#endif
#ifdef USE_RGRS_KICK_HDFL_HT_03
static const unsigned char rgrs_kick_hdfl_ht_03_data[] = {
#include "data/rgrs_kick_hdfl_ht_03.inc"
};
#endif
#ifdef USE_RGRS_KICK_SFFL_HT_03
static const unsigned char rgrs_kick_sffl_ht_03_data[] = {
#include "data/rgrs_kick_sffl_ht_03.inc"
};
#endif
#ifdef USE_RGRS_RTOM_CNFL_HT_03
static const unsigned char rgrs_rtom_cnfl_ht_03_data[] = {
#include "data/rgrs_rtom_cnfl_ht_03.inc"
};
#endif
#ifdef USE_SHKR_HDFL_HT_015_03
static const unsigned char* shkr_hdfl_ht_015_03_data = nullptr;
#endif
#ifdef USE_SHKR_SFFL_HT_015_03
static const unsigned char* shkr_sffl_ht_015_03_data = nullptr;
#endif
#ifdef USE_TAMB_HTFL_HT_015_03
static const unsigned char* tamb_htfl_ht_015_03_data = nullptr;
#endif
#ifdef USE_TAMB_SHFL_HT_015_03
static const unsigned char* tamb_shfl_ht_015_03_data = nullptr;
#endif
#ifdef USE_ZDJN_HAT_C1EGFL_HT_015_01
static const unsigned char zdjn_hat_c1egfl_ht_015_01_data[] = {
#include "data/zdjn_hat_c1egfl_ht_015_01.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C1EGFL_HT_015_02
static const unsigned char zdjn_hat_c1egfl_ht_015_02_data[] = {
#include "data/zdjn_hat_c1egfl_ht_015_02.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C1EGFL_HT_015_03
static const unsigned char zdjn_hat_c1egfl_ht_015_03_data[] = {
#include "data/zdjn_hat_c1egfl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C1FL_HT_015_01
static const unsigned char zdjn_hat_c1fl_ht_015_01_data[] = {
#include "data/zdjn_hat_c1fl_ht_015_01.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C1FL_HT_015_02
static const unsigned char zdjn_hat_c1fl_ht_015_02_data[] = {
#include "data/zdjn_hat_c1fl_ht_015_02.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C1FL_HT_015_03
static const unsigned char zdjn_hat_c1fl_ht_015_03_data[] = {
#include "data/zdjn_hat_c1fl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C2EGFL_HT_015_01
static const unsigned char zdjn_hat_c2egfl_ht_015_01_data[] = {
#include "data/zdjn_hat_c2egfl_ht_015_01.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C2EGFL_HT_015_02
static const unsigned char zdjn_hat_c2egfl_ht_015_02_data[] = {
#include "data/zdjn_hat_c2egfl_ht_015_02.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C2EGFL_HT_015_03
static const unsigned char zdjn_hat_c2egfl_ht_015_03_data[] = {
#include "data/zdjn_hat_c2egfl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C2FL_HT_015_01
static const unsigned char zdjn_hat_c2fl_ht_015_01_data[] = {
#include "data/zdjn_hat_c2fl_ht_015_01.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C2FL_HT_015_02
static const unsigned char zdjn_hat_c2fl_ht_015_02_data[] = {
#include "data/zdjn_hat_c2fl_ht_015_02.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C2FL_HT_015_03
static const unsigned char zdjn_hat_c2fl_ht_015_03_data[] = {
#include "data/zdjn_hat_c2fl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C3EGFL_HT_015_03
static const unsigned char zdjn_hat_c3egfl_ht_015_03_data[] = {
#include "data/zdjn_hat_c3egfl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_C3FL_HT_015_03
static const unsigned char zdjn_hat_c3fl_ht_015_03_data[] = {
#include "data/zdjn_hat_c3fl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_O1EGFL_HT_015_03
static const unsigned char zdjn_hat_o1egfl_ht_015_03_data[] = {
#include "data/zdjn_hat_o1egfl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_O1FL_HT_015_03
static const unsigned char zdjn_hat_o1fl_ht_015_03_data[] = {
#include "data/zdjn_hat_o1fl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_O2EGFL_HT_015_03
static const unsigned char zdjn_hat_o2egfl_ht_015_03_data[] = {
#include "data/zdjn_hat_o2egfl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_O2FL_HT_015_03
static const unsigned char zdjn_hat_o2fl_ht_015_03_data[] = {
#include "data/zdjn_hat_o2fl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_O3EGFL_HT_015_03
static const unsigned char zdjn_hat_o3egfl_ht_015_03_data[] = {
#include "data/zdjn_hat_o3egfl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_O3FL_HT_015_03
static const unsigned char zdjn_hat_o3fl_ht_015_03_data[] = {
#include "data/zdjn_hat_o3fl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_POFL_HT_015_03
static const unsigned char zdjn_hat_pofl_ht_015_03_data[] = {
#include "data/zdjn_hat_pofl_ht_015_03.inc"
};
#endif
#ifdef USE_ZDJN_HAT_PSFL_HT_015_01
static const unsigned char zdjn_hat_psfl_ht_015_01_data[] = {
#include "data/zdjn_hat_psfl_ht_015_01.inc"
};
#endif
#ifdef USE_ZDJN_HAT_PSFL_HT_015_02
static const unsigned char zdjn_hat_psfl_ht_015_02_data[] = {
#include "data/zdjn_hat_psfl_ht_015_02.inc"
};
#endif
#ifdef USE_ZDJN_HAT_PSFL_HT_015_03
static const unsigned char zdjn_hat_psfl_ht_015_03_data[] = {
#include "data/zdjn_hat_psfl_ht_015_03.inc"
};
#endif
#ifdef USE_AMEN_01
static const unsigned char amen_01_data[] = {
#include "data/amen_01.inc"
};
#endif
#ifdef USE_AMEN_02
static const unsigned char amen_02_data[] = {
#include "data/amen_02.inc"
};
#endif
#ifdef USE_AMEN_03
static const unsigned char amen_03_data[] = {
#include "data/amen_03.inc"
};
#endif
#ifdef USE_AMEN_04
static const unsigned char amen_04_data[] = {
#include "data/amen_04.inc"
};
#endif
#ifdef USE_AMEN_05
static const unsigned char amen_05_data[] = {
#include "data/amen_05.inc"
};
#endif
#ifdef USE_AMEN_06
static const unsigned char amen_06_data[] = {
#include "data/amen_06.inc"
};
#endif
#ifdef USE_AMEN_07
static const unsigned char amen_07_data[] = {
#include "data/amen_07.inc"
};
#endif
#ifdef USE_AMEN_08
static const unsigned char amen_08_data[] = {
#include "data/amen_08.inc"
};
#endif
#ifdef USE_AMEN_09
static const unsigned char amen_09_data[] = {
#include "data/amen_09.inc"
};
#endif
#ifdef USE_AMEN_10
static const unsigned char amen_10_data[] = {
#include "data/amen_10.inc"
};
#endif
#ifdef USE_AMEN_11
static const unsigned char amen_11_data[] = {
#include "data/amen_11.inc"
};
#endif
#ifdef USE_AMEN_12
static const unsigned char amen_12_data[] = {
#include "data/amen_12.inc"
};
#endif
#ifdef USE_AMEN_13
static const unsigned char amen_13_data[] = {
#include "data/amen_13.inc"
};
#endif
#ifdef USE_AMEN_14
static const unsigned char amen_14_data[] = {
#include "data/amen_14.inc"
};
#endif
#ifdef USE_AMEN_15
static const unsigned char amen_15_data[] = {
#include "data/amen_15.inc"
};
#endif
#ifdef USE_AMEN_16
static const unsigned char amen_16_data[] = {
#include "data/amen_16.inc"
};
#endif
#ifdef USE_AMEN_17
static const unsigned char amen_17_data[] = {
#include "data/amen_17.inc"
};
#endif
#ifdef USE_AMEN_18
static const unsigned char amen_18_data[] = {
#include "data/amen_18.inc"
};
#endif
#ifdef USE_AMEN_19
static const unsigned char amen_19_data[] = {
#include "data/amen_19.inc"
};
#endif
#ifdef USE_AMEN_20
static const unsigned char amen_20_data[] = {
#include "data/amen_20.inc"
};
#endif
#ifdef USE_AMEN_21
static const unsigned char amen_21_data[] = {
#include "data/amen_21.inc"
};
#endif
#ifdef USE_AMEN_22
static const unsigned char amen_22_data[] = {
#include "data/amen_22.inc"
};
#endif
#ifdef USE_AMEN_23
static const unsigned char amen_23_data[] = {
#include "data/amen_23.inc"
};
#endif
#ifdef USE_AMEN_24
static const unsigned char amen_24_data[] = {
#include "data/amen_24.inc"
};
#endif
#ifdef USE_AMEN_25
static const unsigned char amen_25_data[] = {
#include "data/amen_25.inc"
};
#endif
#ifdef USE_AMEN_26
static const unsigned char amen_26_data[] = {
#include "data/amen_26.inc"
};
#endif
#ifdef USE_AMEN_27
static const unsigned char amen_27_data[] = {
#include "data/amen_27.inc"
};
#endif
#ifdef USE_AMEN_28
static const unsigned char amen_28_data[] = {
#include "data/amen_28.inc"
};
#endif
#ifdef USE_AMEN_29
static const unsigned char amen_29_data[] = {
#include "data/amen_29.inc"
};
#endif
#ifdef USE_AMEN_30
static const unsigned char amen_30_data[] = {
#include "data/amen_30.inc"
};
#endif
#ifdef USE_AMEN_31
static const unsigned char amen_31_data[] = {
#include "data/amen_31.inc"
};
#endif
#ifdef USE_AMEN_32
static const unsigned char amen_32_data[] = {
#include "data/amen_32.inc"
};
#endif
#ifdef USE_AMEN_33
static const unsigned char amen_33_data[] = {
#include "data/amen_33.inc"
};
#endif
#ifdef USE_AMEN_34
static const unsigned char amen_34_data[] = {
#include "data/amen_34.inc"
};
#endif
#ifdef USE_AMEN_35
static const unsigned char amen_35_data[] = {
#include "data/amen_35.inc"
};
#endif
#ifdef USE_AMEN_36
static const unsigned char amen_36_data[] = {
#include "data/amen_36.inc"
};
#endif
#ifdef USE_AMEN_37
static const unsigned char amen_37_data[] = {
#include "data/amen_37.inc"
};
#endif
#ifdef USE_AMEN_38
static const unsigned char amen_38_data[] = {
#include "data/amen_38.inc"
};
#endif
#ifdef USE_AMEN_39
static const unsigned char amen_39_data[] = {
#include "data/amen_39.inc"
};
#endif
#ifdef USE_AMEN_40
static const unsigned char amen_40_data[] = {
#include "data/amen_40.inc"
};
#endif
#ifdef USE_AMEN_41
static const unsigned char amen_41_data[] = {
#include "data/amen_41.inc"
};
#endif
#ifdef USE_AMEN_42
static const unsigned char amen_42_data[] = {
#include "data/amen_42.inc"
};
#endif
#ifdef USE_AMEN_43
static const unsigned char amen_43_data[] = {
#include "data/amen_43.inc"
};
#endif
#ifdef USE_AMEN_44
static const unsigned char amen_44_data[] = {
#include "data/amen_44.inc"
};
#endif
#ifdef USE_AMEN_45
static const unsigned char amen_45_data[] = {
#include "data/amen_45.inc"
};
#endif
#ifdef USE_AMEN_46
static const unsigned char amen_46_data[] = {
#include "data/amen_46.inc"
};
#endif
#ifdef USE_CLAP_808
static const unsigned char clap_808_data[] = {
#include "data/clap_808.inc"
};
#endif
#ifdef USE_CLAP_ANALOG
static const unsigned char clap_analog_data[] = {
#include "data/clap_analog.inc"
};
#endif
#ifdef USE_CLAP_CRUSHED
static const unsigned char clap_crushed_data[] = {
#include "data/clap_crushed.inc"
};
#endif
#ifdef USE_CLAP_FAT
static const unsigned char clap_fat_data[] = {
#include "data/clap_fat.inc"
};
#endif
#ifdef USE_CLAP_SLAPPER
static const unsigned char clap_slapper_data[] = {
#include "data/clap_slapper.inc"
};
#endif
#ifdef USE_CLAP_TAPE
static const unsigned char clap_tape_data[] = {
#include "data/clap_tape.inc"
};
#endif
#ifdef USE_COWBELL_808
static const unsigned char cowbell_808_data[] = {
#include "data/cowbell_808.inc"
};
#endif
#ifdef USE_CRASH_808
static const unsigned char* crash_808_data = nullptr;
#endif
#ifdef USE_CRASH_ACOUSTIC
static const unsigned char crash_acoustic_data[] = {
#include "data/crash_acoustic.inc"
};
#endif
#ifdef USE_CRASH_NOISE
static const unsigned char* crash_noise_data = nullptr;
#endif
#ifdef USE_CRASH_TAPE
static const unsigned char crash_tape_data[] = {
#include "data/crash_tape.inc"
};
#endif
#ifdef USE_HIHAT_808
static const unsigned char* hihat_808_data = nullptr;
#endif
#ifdef USE_HIHAT_ACOUSTIC01
static const unsigned char hihat_acoustic01_data[] = {
#include "data/hihat_acoustic01.inc"
};
#endif
#ifdef USE_HIHAT_ACOUSTIC02
static const unsigned char hihat_acoustic02_data[] = {
#include "data/hihat_acoustic02.inc"
};
#endif
#ifdef USE_HIHAT_ANALOG
static const unsigned char hihat_analog_data[] = {
#include "data/hihat_analog.inc"
};
#endif
#ifdef USE_HIHAT_DIGITAL
static const unsigned char* hihat_digital_data = nullptr;
#endif
#ifdef USE_HIHAT_DIST01
static const unsigned char hihat_dist01_data[] = {
#include "data/hihat_dist01.inc"
};
#endif
#ifdef USE_HIHAT_DIST02
static const unsigned char hihat_dist02_data[] = {
#include "data/hihat_dist02.inc"
};
#endif
#ifdef USE_HIHAT_ELECTRO
static const unsigned char* hihat_electro_data = nullptr;
#endif
#ifdef USE_HIHAT_PLAIN
static const unsigned char* hihat_plain_data = nullptr;
#endif
#ifdef USE_HIHAT_RESO
static const unsigned char* hihat_reso_data = nullptr;
#endif
#ifdef USE_HIHAT_RING
static const unsigned char* hihat_ring_data = nullptr;
#endif
#ifdef USE_KICK_808
static const unsigned char kick_808_data[] = {
#include "data/kick_808.inc"
};
#endif
#ifdef USE_KICK_ACOUSTIC01
static const unsigned char kick_acoustic01_data[] = {
#include "data/kick_acoustic01.inc"
};
#endif
#ifdef USE_KICK_ACOUSTIC02
static const unsigned char kick_acoustic02_data[] = {
#include "data/kick_acoustic02.inc"
};
#endif
#ifdef USE_KICK_BIG
static const unsigned char kick_big_data[] = {
#include "data/kick_big.inc"
};
#endif
#ifdef USE_KICK_CLASSIC
static const unsigned char kick_classic_data[] = {
#include "data/kick_classic.inc"
};
#endif
#ifdef USE_KICK_CULTIVATOR
static const unsigned char kick_cultivator_data[] = {
#include "data/kick_cultivator.inc"
};
#endif
#ifdef USE_KICK_DEEP
static const unsigned char kick_deep_data[] = {
#include "data/kick_deep.inc"
};
#endif
#ifdef USE_KICK_DRY
static const unsigned char kick_dry_data[] = {
#include "data/kick_dry.inc"
};
#endif
#ifdef USE_KICK_ELECTRO01
static const unsigned char kick_electro01_data[] = {
#include "data/kick_electro01.inc"
};
#endif
#ifdef USE_KICK_ELECTRO02
static const unsigned char kick_electro02_data[] = {
#include "data/kick_electro02.inc"
};
#endif
#ifdef USE_KICK_FLOPPY
static const unsigned char kick_floppy_data[] = {
#include "data/kick_floppy.inc"
};
#endif
#ifdef USE_KICK_GRITTY
static const unsigned char kick_gritty_data[] = {
#include "data/kick_gritty.inc"
};
#endif
#ifdef USE_KICK_HEAVY
static const unsigned char kick_heavy_data[] = {
#include "data/kick_heavy.inc"
};
#endif
#ifdef USE_KICK_NEWWAVE
static const unsigned char kick_newwave_data[] = {
#include "data/kick_newwave.inc"
};
#endif
#ifdef USE_KICK_OLDSCHOOL
static const unsigned char kick_oldschool_data[] = {
#include "data/kick_oldschool.inc"
};
#endif
#ifdef USE_KICK_PLAIN
static const unsigned char kick_plain_data[] = {
#include "data/kick_plain.inc"
};
#endif
#ifdef USE_KICK_SLAPBACK
static const unsigned char kick_slapback_data[] = {
#include "data/kick_slapback.inc"
};
#endif
#ifdef USE_KICK_SOFTY
static const unsigned char kick_softy_data[] = {
#include "data/kick_softy.inc"
};
#endif
#ifdef USE_KICK_STOMP
static const unsigned char kick_stomp_data[] = {
#include "data/kick_stomp.inc"
};
#endif
#ifdef USE_KICK_TAPE
static const unsigned char kick_tape_data[] = {
#include "data/kick_tape.inc"
};
#endif
#ifdef USE_KICK_THUMP
static const unsigned char kick_thump_data[] = {
#include "data/kick_thump.inc"
};
#endif
#ifdef USE_KICK_TIGHT
static const unsigned char kick_tight_data[] = {
#include "data/kick_tight.inc"
};
#endif
#ifdef USE_KICK_TRON
static const unsigned char kick_tron_data[] = {
#include "data/kick_tron.inc"
};
#endif
#ifdef USE_KICK_VINYL01
static const unsigned char kick_vinyl01_data[] = {
#include "data/kick_vinyl01.inc"
};
#endif
#ifdef USE_KICK_VINYL02
static const unsigned char kick_vinyl02_data[] = {
#include "data/kick_vinyl02.inc"
};
#endif
#ifdef USE_KICK_ZAPPER
static const unsigned char kick_zapper_data[] = {
#include "data/kick_zapper.inc"
};
#endif
#ifdef USE_OPENHAT_808
static const unsigned char* openhat_808_data = nullptr;
#endif
#ifdef USE_OPENHAT_ACOUSTIC01
static const unsigned char openhat_acoustic01_data[] = {
#include "data/openhat_acoustic01.inc"
};
#endif
#ifdef USE_OPENHAT_ANALOG
static const unsigned char openhat_analog_data[] = {
#include "data/openhat_analog.inc"
};
#endif
#ifdef USE_OPENHAT_SLICK
static const unsigned char* openhat_slick_data = nullptr;
#endif
#ifdef USE_OPENHAT_TIGHT
static const unsigned char openhat_tight_data[] = {
#include "data/openhat_tight.inc"
};
#endif
#ifdef USE_PERC_808
static const unsigned char perc_808_data[] = {
#include "data/perc_808.inc"
};
#endif
#ifdef USE_PERC_CHIRPY
static const unsigned char* perc_chirpy_data = nullptr;
#endif
#ifdef USE_PERC_HOLLOW
static const unsigned char perc_hollow_data[] = {
#include "data/perc_hollow.inc"
};
#endif
#ifdef USE_PERC_LASER
static const unsigned char perc_laser_data[] = {
#include "data/perc_laser.inc"
};
#endif
#ifdef USE_PERC_METAL
static const unsigned char perc_metal_data[] = {
#include "data/perc_metal.inc"
};
#endif
#ifdef USE_PERC_NASTY
static const unsigned char perc_nasty_data[] = {
#include "data/perc_nasty.inc"
};
#endif
#ifdef USE_PERC_SHORT
static const unsigned char perc_short_data[] = {
#include "data/perc_short.inc"
};
#endif
#ifdef USE_PERC_TAMBO
static const unsigned char* perc_tambo_data = nullptr;
#endif
#ifdef USE_PERC_TRIBAL
static const unsigned char perc_tribal_data[] = {
#include "data/perc_tribal.inc"
};
#endif
#ifdef USE_PERC_WEIRDO
static const unsigned char perc_weirdo_data[] = {
#include "data/perc_weirdo.inc"
};
#endif
#ifdef USE_RIDE_ACOUSTIC01
static const unsigned char ride_acoustic01_data[] = {
#include "data/ride_acoustic01.inc"
};
#endif
#ifdef USE_RIDE_ACOUSTIC02
static const unsigned char ride_acoustic02_data[] = {
#include "data/ride_acoustic02.inc"
};
#endif
#ifdef USE_SHAKER_ANALOG
static const unsigned char shaker_analog_data[] = {
#include "data/shaker_analog.inc"
};
#endif
#ifdef USE_SHAKER_SHUFFLE
static const unsigned char* shaker_shuffle_data = nullptr;
#endif
#ifdef USE_SHAKER_SUCKUP
static const unsigned char* shaker_suckup_data = nullptr;
#endif
#ifdef USE_SNARE_808
static const unsigned char snare_808_data[] = {
#include "data/snare_808.inc"
};
#endif
#ifdef USE_SNARE_ACOUSTIC01
static const unsigned char snare_acoustic01_data[] = {
#include "data/snare_acoustic01.inc"
};
#endif
#ifdef USE_SNARE_ACOUSTIC02
static const unsigned char snare_acoustic02_data[] = {
#include "data/snare_acoustic02.inc"
};
#endif
#ifdef USE_SNARE_ANALOG
static const unsigned char snare_analog_data[] = {
#include "data/snare_analog.inc"
};
#endif
#ifdef USE_SNARE_BIG
static const unsigned char snare_big_data[] = {
#include "data/snare_big.inc"
};
#endif
#ifdef USE_SNARE_BLOCK
static const unsigned char snare_block_data[] = {
#include "data/snare_block.inc"
};
#endif
#ifdef USE_SNARE_BRUTE
static const unsigned char snare_brute_data[] = {
#include "data/snare_brute.inc"
};
#endif
#ifdef USE_SNARE_DIST01
static const unsigned char snare_dist01_data[] = {
#include "data/snare_dist01.inc"
};
#endif
#ifdef USE_SNARE_DIST02
static const unsigned char snare_dist02_data[] = {
#include "data/snare_dist02.inc"
};
#endif
#ifdef USE_SNARE_DIST03
static const unsigned char snare_dist03_data[] = {
#include "data/snare_dist03.inc"
};
#endif
#ifdef USE_SNARE_ELECTRO
static const unsigned char snare_electro_data[] = {
#include "data/snare_electro.inc"
};
#endif
#ifdef USE_SNARE_LOFI01
static const unsigned char snare_lofi01_data[] = {
#include "data/snare_lofi01.inc"
};
#endif
#ifdef USE_SNARE_LOFI02
static const unsigned char snare_lofi02_data[] = {
#include "data/snare_lofi02.inc"
};
#endif
#ifdef USE_SNARE_MODULAR
static const unsigned char snare_modular_data[] = {
#include "data/snare_modular.inc"
};
#endif
#ifdef USE_SNARE_NOISE
static const unsigned char snare_noise_data[] = {
#include "data/snare_noise.inc"
};
#endif
#ifdef USE_SNARE_PINCH
static const unsigned char snare_pinch_data[] = {
#include "data/snare_pinch.inc"
};
#endif
#ifdef USE_SNARE_PUNCH
static const unsigned char snare_punch_data[] = {
#include "data/snare_punch.inc"
};
#endif
#ifdef USE_SNARE_SMASHER
static const unsigned char snare_smasher_data[] = {
#include "data/snare_smasher.inc"
};
#endif
#ifdef USE_SNARE_SUMO
static const unsigned char snare_sumo_data[] = {
#include "data/snare_sumo.inc"
};
#endif
#ifdef USE_SNARE_TAPE
static const unsigned char snare_tape_data[] = {
#include "data/snare_tape.inc"
};
#endif
#ifdef USE_SNARE_VINYL01
static const unsigned char snare_vinyl01_data[] = {
#include "data/snare_vinyl01.inc"
};
#endif
#ifdef USE_SNARE_VINYL02
static const unsigned char snare_vinyl02_data[] = {
#include "data/snare_vinyl02.inc"
};
#endif
#ifdef USE_TOM_808
static const unsigned char tom_808_data[] = {
#include "data/tom_808.inc"
};
#endif
#ifdef USE_TOM_ACOUSTIC01
static const unsigned char tom_acoustic01_data[] = {
#include "data/tom_acoustic01.inc"
};
#endif
#ifdef USE_TOM_ACOUSTIC02
static const unsigned char tom_acoustic02_data[] = {
#include "data/tom_acoustic02.inc"
};
#endif
#ifdef USE_TOM_ANALOG
static const unsigned char tom_analog_data[] = {
#include "data/tom_analog.inc"
};
#endif
#ifdef USE_TOM_CHIPTUNE
static const unsigned char tom_chiptune_data[] = {
#include "data/tom_chiptune.inc"
};
#endif
#ifdef USE_TOM_FM
static const unsigned char tom_fm_data[] = {
#include "data/tom_fm.inc"
};
#endif
#ifdef USE_TOM_LOFI
static const unsigned char tom_lofi_data[] = {
#include "data/tom_lofi.inc"
};
#endif
#ifdef USE_TOM_ROTOTOM
static const unsigned char tom_rototom_data[] = {
#include "data/tom_rototom.inc"
};
#endif
#ifdef USE_TOM_SHORT
static const unsigned char tom_short_data[] = {
#include "data/tom_short.inc"
};
#endif
