#ifdef USE_AMEN_01
{
#include "struct/amen_01.inc"
},
#endif
#ifdef USE_AMEN_02
{
#include "struct/amen_02.inc"
},
#endif
#ifdef USE_AMEN_03
{
#include "struct/amen_03.inc"
},
#endif
#ifdef USE_AMEN_04
{
#include "struct/amen_04.inc"
},
#endif
#ifdef USE_AMEN_05
{
#include "struct/amen_05.inc"
},
#endif
#ifdef USE_AMEN_06
{
#include "struct/amen_06.inc"
},
#endif
#ifdef USE_AMEN_07
{
#include "struct/amen_07.inc"
},
#endif
#ifdef USE_AMEN_08
{
#include "struct/amen_08.inc"
},
#endif
#ifdef USE_AMEN_09
{
#include "struct/amen_09.inc"
},
#endif
#ifdef USE_AMEN_10
{
#include "struct/amen_10.inc"
},
#endif
#ifdef USE_AMEN_11
{
#include "struct/amen_11.inc"
},
#endif
#ifdef USE_AMEN_12
{
#include "struct/amen_12.inc"
},
#endif
#ifdef USE_AMEN_13
{
#include "struct/amen_13.inc"
},
#endif
#ifdef USE_AMEN_14
{
#include "struct/amen_14.inc"
},
#endif
#ifdef USE_AMEN_15
{
#include "struct/amen_15.inc"
},
#endif
#ifdef USE_AMEN_16
{
#include "struct/amen_16.inc"
},
#endif
#ifdef USE_AMEN_17
{
#include "struct/amen_17.inc"
},
#endif
#ifdef USE_AMEN_18
{
#include "struct/amen_18.inc"
},
#endif
#ifdef USE_AMEN_19
{
#include "struct/amen_19.inc"
},
#endif
#ifdef USE_AMEN_20
{
#include "struct/amen_20.inc"
},
#endif
#ifdef USE_AMEN_21
{
#include "struct/amen_21.inc"
},
#endif
#ifdef USE_AMEN_22
{
#include "struct/amen_22.inc"
},
#endif
#ifdef USE_AMEN_23
{
#include "struct/amen_23.inc"
},
#endif
#ifdef USE_AMEN_24
{
#include "struct/amen_24.inc"
},
#endif
#ifdef USE_AMEN_25
{
#include "struct/amen_25.inc"
},
#endif
#ifdef USE_AMEN_26
{
#include "struct/amen_26.inc"
},
#endif
#ifdef USE_AMEN_27
{
#include "struct/amen_27.inc"
},
#endif
#ifdef USE_AMEN_28
{
#include "struct/amen_28.inc"
},
#endif
#ifdef USE_AMEN_29
{
#include "struct/amen_29.inc"
},
#endif
#ifdef USE_AMEN_30
{
#include "struct/amen_30.inc"
},
#endif
#ifdef USE_AMEN_31
{
#include "struct/amen_31.inc"
},
#endif
#ifdef USE_AMEN_32
{
#include "struct/amen_32.inc"
},
#endif
#ifdef USE_AMEN_33
{
#include "struct/amen_33.inc"
},
#endif
#ifdef USE_AMEN_34
{
#include "struct/amen_34.inc"
},
#endif
#ifdef USE_AMEN_35
{
#include "struct/amen_35.inc"
},
#endif
#ifdef USE_AMEN_36
{
#include "struct/amen_36.inc"
},
#endif
#ifdef USE_AMEN_37
{
#include "struct/amen_37.inc"
},
#endif
#ifdef USE_AMEN_38
{
#include "struct/amen_38.inc"
},
#endif
#ifdef USE_AMEN_39
{
#include "struct/amen_39.inc"
},
#endif
#ifdef USE_AMEN_40
{
#include "struct/amen_40.inc"
},
#endif
#ifdef USE_AMEN_41
{
#include "struct/amen_41.inc"
},
#endif
#ifdef USE_AMEN_42
{
#include "struct/amen_42.inc"
},
#endif
#ifdef USE_AMEN_43
{
#include "struct/amen_43.inc"
},
#endif
#ifdef USE_AMEN_44
{
#include "struct/amen_44.inc"
},
#endif
#ifdef USE_AMEN_45
{
#include "struct/amen_45.inc"
},
#endif
#ifdef USE_AMEN_46
{
#include "struct/amen_46.inc"
},
#endif
